// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yavaypifpwfvrqbvjbqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdmF5cGlmcHdmdnJxYnZqYnF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MDUxNzgsImV4cCI6MjA3NDE4MTE3OH0.4lvKfVTPED1EQ0GEHcyFdr_j-1ZfK7yIIA9TvK4d88k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});